//! # Linux Multi-Tiered DNS Leak Protection
//!
//! Multi-tiered DNS resolver:
//! 1. `systemd-resolved` via `resolvectl` / D-Bus (using `~.` routing domain priority).
//! 2. Fallback to `/etc/resolv.conf` backup and atomic restoration.

use crate::error::DnsError;
use std::fs;
use std::path::PathBuf;
use tracing::{debug, info, warn};

/// Linux DNS Manager.
pub struct LinuxDnsManager {
    resolv_conf_backup: Option<String>,
    active_iface: Option<String>,
}

impl Default for LinuxDnsManager {
    fn default() -> Self {
        Self::new()
    }
}

impl LinuxDnsManager {
    /// Creates a new Linux DNS manager.
    pub fn new() -> Self {
        Self {
            resolv_conf_backup: None,
            active_iface: None,
        }
    }

    /// Configures DNS servers on the tunnel interface and enforces routing domain priority (`~.`).
    pub fn configure_dns(
        &mut self,
        tunnel_iface: &str,
        dns_servers: &[String],
    ) -> Result<(), DnsError> {
        info!(
            "Configuring DNS servers ({:?}) on interface '{}'",
            dns_servers, tunnel_iface
        );

        if dns_servers.is_empty() {
            return Ok(());
        }

        self.active_iface = Some(tunnel_iface.to_string());

        // Tier 1: Try systemd-resolved via `resolvectl`
        let mut cmd = std::process::Command::new("resolvectl");
        cmd.arg("dns").arg(tunnel_iface);
        for s in dns_servers {
            cmd.arg(s);
        }

        if let Ok(status) = cmd.status() {
            if status.success() {
                // Set default routing domain priority (`~.`)
                let _ = std::process::Command::new("resolvectl")
                    .args(["domain", tunnel_iface, "~."])
                    .status();
                info!(
                    "DNS successfully configured via systemd-resolved for {}",
                    tunnel_iface
                );
                return Ok(());
            }
        }

        // Tier 2: Fallback to /etc/resolv.conf backup & overwrite
        warn!("systemd-resolved unavailable; falling back to /etc/resolv.conf update");
        self.apply_resolv_conf_fallback(dns_servers)?;

        Ok(())
    }

    /// Restores previous DNS configuration upon VPN disconnection.
    pub fn restore_dns(&mut self) -> Result<(), DnsError> {
        info!("Restoring original DNS configuration");

        if let Some(ref iface) = self.active_iface {
            let _ = std::process::Command::new("resolvectl")
                .args(["revert", iface])
                .status();
        }

        if let Some(ref backup) = self.resolv_conf_backup {
            let resolv_path = PathBuf::from("/etc/resolv.conf");
            if let Err(e) = fs::write(&resolv_path, backup) {
                warn!("Failed to restore /etc/resolv.conf: {}", e);
            } else {
                debug!("Restored original /etc/resolv.conf");
            }
            self.resolv_conf_backup = None;
        }

        self.active_iface = None;
        Ok(())
    }

    /// Overwrites `/etc/resolv.conf` with backup.
    fn apply_resolv_conf_fallback(&mut self, dns_servers: &[String]) -> Result<(), DnsError> {
        let resolv_path = PathBuf::from("/etc/resolv.conf");
        if resolv_path.exists() && self.resolv_conf_backup.is_none() {
            if let Ok(content) = fs::read_to_string(&resolv_path) {
                self.resolv_conf_backup = Some(content);
            }
        }

        let mut new_content = String::from("# Generated by VPNHub Daemon\n");
        for s in dns_servers {
            new_content.push_str(&format!("nameserver {}\n", s));
        }

        fs::write(&resolv_path, new_content).map_err(|e| {
            DnsError::ResolvConfFailed(format!("Failed to write /etc/resolv.conf: {}", e))
        })?;

        Ok(())
    }
}
