import { VpnProfile, LogEntry, AppRule, IpDomainRule } from "../types/vpn";

export const INITIAL_PROFILES: VpnProfile[] = [
  {
    id: "sg-prod-01",
    name: "Singapore - Equinix SG1",
    protocol: "wireguard",
    serverHost: "103.21.244.18",
    serverPort: 51820,
    serverCountry: "Singapore",
    serverCity: "Jurong East",
    serverFlag: "🇸🇬",
    virtualIp: "10.8.0.42/32",
    assignedIp: "103.21.244.18",
    isFavorite: true,
    tags: ["Production", "Low-Latency", "Asia-Pacific"],
    lastConnected: "2 mins ago",
    pingMs: 24,
    credentials: {
      hasPrivateKey: true,
    },
    rawConfig: `[Interface]\nPrivateKey = aGVwaGFlc3R1cy1zZWNyZXQta2V5LTEyMzQ1Njc4OTA=\nAddress = 10.8.0.42/24\nDNS = 1.1.1.1\n\n[Peer]\nPublicKey = c2ctcHJvZC0wMS1wdWJsaWMta2V5LWFzZGYxMjM=\nEndpoint = 103.21.244.18:51820\nAllowedIPs = 0.0.0.0/0\nPersistentKeepalive = 25`,
  },
  {
    id: "us-east-prod",
    name: "US East - AWS Virginia",
    protocol: "wireguard",
    serverHost: "54.210.88.192",
    serverPort: 51820,
    serverCountry: "United States",
    serverCity: "Ashburn, VA",
    serverFlag: "🇺🇸",
    virtualIp: "10.8.1.15/32",
    isFavorite: true,
    tags: ["Production", "Cloud", "AWS"],
    lastConnected: "1 day ago",
    pingMs: 165,
    credentials: {
      hasPrivateKey: true,
    },
  },
  {
    id: "de-corp-vpn",
    name: "Frankfurt - HQ Gateway",
    protocol: "openvpn_udp",
    serverHost: "185.120.44.5",
    serverPort: 1194,
    serverCountry: "Germany",
    serverCity: "Frankfurt am Main",
    serverFlag: "🇩🇪",
    virtualIp: "10.100.4.88/24",
    isFavorite: false,
    tags: ["Office", "Corporate", "Intranet"],
    lastConnected: "3 days ago",
    pingMs: 142,
    credentials: {
      username: "haipn@hephaestus.internal",
      hasPassword: true,
      hasCert: true,
    },
  },
  {
    id: "jp-tokyo-02",
    name: "Tokyo - NTT Ginza",
    protocol: "wireguard",
    serverHost: "133.242.18.99",
    serverPort: 51820,
    serverCountry: "Japan",
    serverCity: "Tokyo",
    serverFlag: "🇯🇵",
    virtualIp: "10.8.2.77/32",
    isFavorite: true,
    tags: ["Staging", "Tokyo-DC"],
    lastConnected: "5 hours ago",
    pingMs: 48,
    credentials: {
      hasPrivateKey: true,
    },
  },
  {
    id: "uk-london-sec",
    name: "London - Telehouse North",
    protocol: "openvpn_tcp",
    serverHost: "194.73.112.50",
    serverPort: 443,
    serverCountry: "United Kingdom",
    serverCity: "London Docklands",
    serverFlag: "🇬🇧",
    virtualIp: "10.200.1.33/24",
    isFavorite: false,
    tags: ["Stealth", "TCP-Over-SSL", "Europe"],
    lastConnected: "1 week ago",
    pingMs: 178,
    credentials: {
      username: "vpnhub_client",
      hasPassword: true,
    },
  },
];

export const INITIAL_LOGS: LogEntry[] = [
  {
    id: "log-1",
    timestamp: "23:15:02.110",
    level: "INFO",
    source: "DAEMON_CORE",
    message: "VPNHub System Daemon v0.1.0 (x86_64-unknown-linux-gnu) initialized successfully",
  },
  {
    id: "log-2",
    timestamp: "23:15:02.145",
    level: "INFO",
    source: "IPC_TRANSPORT",
    message: "Unix Domain Socket bound at /run/vpnhub/daemon.sock (permissions: 0660 root:vpnhub)",
  },
  {
    id: "log-3",
    timestamp: "23:15:02.180",
    level: "INFO",
    source: "FIREWALL_NFT",
    message: "Initialized nftables table inet vpnhub_filter with base chains (killswitch=INACTIVE)",
  },
  {
    id: "log-4",
    timestamp: "23:20:11.890",
    level: "DEBUG",
    source: "WIREGUARD_DRV",
    message: "Kernel module wireguard.ko detected. Generic netlink family ID: 34",
  },
  {
    id: "log-5",
    timestamp: "23:22:45.300",
    level: "INFO",
    source: "ROUTING_ENGINE",
    message: "Default gateway resolved: 192.168.1.1 via interface eno1 (metric 100)",
  },
];

export const INITIAL_APP_RULES: AppRule[] = [
  {
    id: "app-chrome",
    name: "Google Chrome",
    path: "/usr/bin/google-chrome-stable",
    icon: "🌐",
    mode: "route_vpn",
    enabled: true,
  },
  {
    id: "app-slack",
    name: "Slack Workspaces",
    path: "/usr/bin/slack",
    icon: "💬",
    mode: "route_vpn",
    enabled: true,
  },
  {
    id: "app-docker",
    name: "Docker Desktop Engine",
    path: "/usr/bin/dockerd",
    icon: "🐳",
    mode: "bypass",
    enabled: true,
  },
  {
    id: "app-steam",
    name: "Steam Client & Gaming Services",
    path: "/usr/bin/steam",
    icon: "🎮",
    mode: "bypass",
    enabled: true,
  },
  {
    id: "app-terminal",
    name: "GNOME Terminal / SSH",
    path: "/usr/bin/gnome-terminal",
    icon: "💻",
    mode: "route_vpn",
    enabled: false,
  },
];

export const INITIAL_IP_RULES: IpDomainRule[] = [
  {
    id: "rule-cidr-1",
    target: "10.0.0.0/8",
    type: "cidr",
    description: "Corporate VPC Subnets",
    mode: "route_vpn",
    enabled: true,
  },
  {
    id: "rule-cidr-2",
    target: "192.168.1.0/24",
    type: "cidr",
    description: "Local Area Home Network (LAN Bypass)",
    mode: "bypass",
    enabled: true,
  },
  {
    id: "rule-dom-1",
    target: "*.internal.company.com",
    type: "domain",
    description: "Internal Company Microservices",
    mode: "route_vpn",
    enabled: true,
  },
  {
    id: "rule-dom-2",
    target: "*.netflix.com",
    type: "domain",
    description: "Direct Streaming Bypass",
    mode: "bypass",
    enabled: false,
  },
];
